const COUNTER_INCREMENT = 'COUNTER_INCREMENT'
const REQUEST_CREATE_AUTH = 'REQUEST_CREATE_AUTH'
const REQUEST_CREATE_AUTH_SUCCESS = 'REQUEST_CREATE_AUTH_SUCCESS'
const REQUEST_CREATE_AUTH_FAILURE = 'REQUEST_CREATE_AUTH_FAILURE'

export default {
  COUNTER_INCREMENT,
  REQUEST_CREATE_AUTH,
  REQUEST_CREATE_AUTH_SUCCESS,
  REQUEST_CREATE_AUTH_FAILURE
}
