export const COUNTER_INCREMENT = 'COUNTER_INCREMENT'

export const REQUEST_CREATE_AUTH = 'REQUEST_CREATE_AUTH'
export const REQUEST_CREATE_AUTH_SUCCESS = 'REQUEST_CREATE_AUTH_SUCCESS'
export const REQUEST_CREATE_AUTH_FAILURE = 'REQUEST_CREATE_AUTH_FAILURE'
export const REQUEST_DELETE_AUTH_SUCCESS = 'REQUEST_DELETE_AUTH_SUCCESS'

export const REQUEST_POSTS = 'REQUEST_POSTS'
export const REQUEST_POSTS_SUCCESS = 'REQUEST_POSTS_SUCCESS'
export const REQUEST_POSTS_FAILURE = 'REQUEST_POSTS_FAILURE'

export const TOGGLE_OVERLAY = 'TOGGLE_OVERLAY'
export const TOGGLE_MODAL_LOGIN = 'TOGGLE_MODAL_LOGIN'
export const TOGGLE_MODAL_POST = 'TOGGLE_MODAL_POST'
